### PR TITLE
Update dependencies.rst

### PR DESCRIPTION
**Pull request by Dexus**
**What**:

Add missing informations

**Why**:

Because it not work from fresh Debian

**Checklist**:

- [x] Documentation

### CODE REVIEW

**Comment by y0urself** [comment]
Did you use debian buster?

**Comment by bjoernricks** [comment]
It works but you'll get some warnings about the psutils Version. I wanted to investigate the issue but forgot about it.

**Comment by Dexus** [comment]
> Did you use debian buster?

Yes

> It works but you'll get some warnings about the psutils Version. I wanted to investigate the issue but forgot about it.

It may work if you not check for exit codes when you build packages and other stuff like Docker images. I write all my bash scripts with `set -Eeuo pipefail` and then you get a broken script - when there are broken sub-scripts and tools.

**Review by bjoernricks — CHANGES_REQUESTED** [review]
Requiring psutil in version 5.7 was a mistake. The version in Debian buster (5.5) will still work. So I am currently unsure if this PR should be applied.

**Comment by Dexus** [comment]
I leave it up to your decision. Merged it, leave the PR open or close it.

**Comment by y0urself** [comment]
> Requiring psutil in version 5.7 was a mistake. The version in Debian buster (5.5) will still work. So I am currently unsure if this PR should be applied.

I guess changing the dependencies and make the doc valid for next release should be valid, so we do not need the PR.

**Comment by bjoernricks** [comment]
We have lowered the psutil dependency with https://github.com/greenbone/ospd-openvas/pull/490 This will be included in the next release. Therefore I am closing here.

**Pull request closed without merging**
